AWSTemplateFormatVersion: '2010-09-09'
Description: 'SRE Lab: EKS Managed Node Group (Worker Nodes) - Multi AZ'

Parameters:
  ClusterName:
    Type: String
    Description: Name of the EKS Cluster created in step 02
  SubnetPrivate1:
    Type: String
  SubnetPrivate2:
    Type: String

Resources:
  # 1. Permissão de Segurança das Máquinas (IAM Role)
  NodeInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly

  # 2. O Grupo de Máquinas (Auto Scaling Group Gerenciado)
  EksNodeGroup:
    Type: AWS::EKS::Nodegroup
    Properties:
      ClusterName: !Ref ClusterName
      NodeRole: !GetAtt NodeInstanceRole.Arn
      NodegroupName: sre-lab-nodes
      Subnets:
        - !Ref SubnetPrivate1
        - !Ref SubnetPrivate2
      InstanceTypes:
        - t3.medium
      ScalingConfig:
        MinSize: 1
        DesiredSize: 2
        MaxSize: 3
      UpdateConfig:
        MaxUnavailable: 1 # Garante que durante atualizações, apenas 1 nó fique offline por vez

Outputs:
  NodeGroupName:
    Value: !Ref EksNodeGroup