version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logando no ECR..."
      - REPOSITORY_URI=545009864726.dkr.ecr.us-east-1.amazonaws.com/hello-sre-repo
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $REPOSITORY_URI
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo "Construindo a imagem..."
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo "Fazendo o push da imagem..."
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "Gerando imagedefinitions.json..."
      - |
        cat <<EOF > imagedefinitions.json
        [
          {
            "name": "hello-container",
            "imageUri": "${REPOSITORY_URI}:${IMAGE_TAG}"
          }
        ]
        EOF
      - echo "Conteúdo do arquivo gerado:"
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json